#!/bin/bash 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pr_2016.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/tmmn_2016.nc
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/pet_2016.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm100_2016.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1979.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1980.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1981.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1982.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1983.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1984.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1985.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1986.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1987.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1988.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1989.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1990.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1991.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1992.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1993.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1994.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1995.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1996.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1997.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1998.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_1999.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2000.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2001.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2002.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2003.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2004.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2005.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2006.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2007.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2008.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2009.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2010.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2011.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2012.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2013.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2014.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2015.nc 
wget -nc -c -nd http://northwestknowledge.net/metdata/data/fm1000_2016.nc 
